// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/rkcloudchain/rksync/protos/identity.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SerializedIdentity struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IdBytes              []byte   `protobuf:"bytes,2,opt,name=id_bytes,json=idBytes,proto3" json:"id_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedIdentity) Reset()         { *m = SerializedIdentity{} }
func (m *SerializedIdentity) String() string { return proto.CompactTextString(m) }
func (*SerializedIdentity) ProtoMessage()    {}
func (*SerializedIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfba01b5c7988b92, []int{0}
}

func (m *SerializedIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedIdentity.Unmarshal(m, b)
}
func (m *SerializedIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedIdentity.Marshal(b, m, deterministic)
}
func (m *SerializedIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedIdentity.Merge(m, src)
}
func (m *SerializedIdentity) XXX_Size() int {
	return xxx_messageInfo_SerializedIdentity.Size(m)
}
func (m *SerializedIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedIdentity proto.InternalMessageInfo

func (m *SerializedIdentity) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SerializedIdentity) GetIdBytes() []byte {
	if m != nil {
		return m.IdBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*SerializedIdentity)(nil), "protos.SerializedIdentity")
}

func init() {
	proto.RegisterFile("github.com/rkcloudchain/rksync/protos/identity.proto", fileDescriptor_bfba01b5c7988b92)
}

var fileDescriptor_bfba01b5c7988b92 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0xca, 0x4e, 0xce, 0xc9, 0x2f, 0x4d, 0x49, 0xce,
	0x48, 0xcc, 0xcc, 0xd3, 0x2f, 0xca, 0x2e, 0xae, 0xcc, 0x4b, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9,
	0x2f, 0xd6, 0xcf, 0x4c, 0x49, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0xd4, 0x03, 0xf3, 0x85, 0xd8, 0x20,
	0xc2, 0x4a, 0x1e, 0x5c, 0x42, 0xc1, 0xa9, 0x45, 0x99, 0x89, 0x39, 0x99, 0x55, 0xa9, 0x29, 0x9e,
	0x50, 0x35, 0x42, 0xe2, 0x5c, 0xec, 0x79, 0xf9, 0x29, 0xa9, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x6c, 0x20, 0xae, 0x67, 0x8a, 0x90, 0x24, 0x17, 0x47, 0x66, 0x4a, 0x7c,
	0x52, 0x65, 0x49, 0x6a, 0xb1, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x7b, 0x66, 0x8a, 0x13,
	0x88, 0xeb, 0xa4, 0x1e, 0xa5, 0x4a, 0x94, 0x4b, 0x92, 0x20, 0x56, 0x1b, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xae, 0x1c, 0xb9, 0x01, 0xb9, 0x00, 0x00, 0x00,
}
